---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-knative-jenkins-deployer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-knative-jenkins-deployer-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: example-knative-jenkins-deployer-role
subjects:
  - kind: ServiceAccount
    name: example-knative-jenkins-deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-knative-jenkins-deployer-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - "*"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
