apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: todo
spec:
  template:
    spec:
      containers:
        - image: syntasso/sample-todo-app
          ports:
            - containerPort: 8080
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.acid-example-postgresql.credentials.postgresql.acid.zalan.do
                  key: password
            - name: PGHOST
              value: acid-example-postgresql.default.svc.cluster.local
            - name: DBNAME
              value: bestdb
