podTemplate(
  serviceAccount: 'example-knative-jenkins-deployer',
  containers: [
    containerTemplate(name: 'deploy', image: 'bitnami/kubectl:1.22.13', command: 'sleep', args: '99d', runAsUser: '0')
  ]) {

		node(POD_LABEL) {
			stage('deploy') {
				git branch: 'workshop-refactor', url: 'https://github.com/syntasso/sample-golang-app.git'
				container('deploy') {
					sh '''
					kubectl apply --filename ./k8s/app.yaml
					until [ "$(curl -s -o /dev/null -w "%{http_code}" -H "host: todo.local.gd" nginx-nginx-ingress.default.svc.cluster.local)" -eq "200" ]
					do
						sleep 2
					done
					'''
				}
			}
		}
}


