podTemplate(yaml: '''
              apiVersion: v1
              kind: Pod
              spec:
                serviceAccountName: example-knative-jenkins-deployer
                containers:
                - name: kubectl
                  image: bitnami/kubectl:1.22.13
                  imagePullPolicy: Always
                  command:
                  - sleep
                  args:
                  - 99d
                  securityContext:
                    runAsUser: 0
'''
  ) {

  node(POD_LABEL) {
    stage('Deploy application') {
      git branch: 'main', url: 'https://github.com/syntasso/sample-golang-app.git'
      container('kubectl') {
        sh '''
        kubectl apply --filename ./k8s/serving.yaml
        until [ "$(curl -s -o /dev/null -w "%{http_code}" -H "host: todo.default.local.gd" kourier.kourier-system.svc.cluster.local)" -eq "200" ]
        do
          sleep 2
        done
        '''
      }
    }
  }
}
